<style>
.salary_page{padding:18px}.salary_toolbar{margin-bottom:12px}.salary_toolbar .btn{display:inline-block;background:#64748b;color:#fff;padding:0 14px;line-height:30px;height:30px;text-decoration:none;margin-right:8px}.salary_tip{border:1px solid #d9e2ef;background:#fbfdff;padding:10px 14px;margin-bottom:12px;color:#475569}.salary_scroll{overflow:auto;border:1px solid #d9e2ef;background:#fff}.salary_table{width:100%;border-collapse:collapse;min-width:1100px}.salary_table th{color:#334155;font-weight:normal;text-align:left;padding:8px;border-bottom:1px solid #d9e2ef}.salary_table td{padding:8px;border-bottom:1px solid #edf2f7;color:#475569}.salary_table tr:hover td{box-shadow:inset 0 0 0 9999px rgba(100,116,139,.08)}.salary_name{width:110px;min-width:110px}.salary_mobile{width:120px;min-width:120px}.salary_department{width:160px;min-width:160px}.salary_project{width:116px;min-width:116px}.salary_two_line{display:-webkit-box;-webkit-box-orient:vertical;-webkit-line-clamp:2;overflow:hidden;max-height:36px;line-height:18px;white-space:normal;word-break:break-all}.salary_mobile .salary_two_line{display:block;white-space:nowrap;text-overflow:ellipsis}.archive_summary{background:#eaf3ff}.archive_earning{background:#edf9f1}.archive_deduction{background:#fff4e8}.archive_statistic{background:#f3f0ff}.archive_data{background:#edf7f8}.archive_note{background:#fffbe8}.archive_other{background:#f8fafc}
</style>
<div class="full_box">
	{{ partial('salary_primary_navigation') }}
	<div class="salary_secondary_navigation"><a href="{{helper.createUrl(['p':'salary/archive'])}}">归档记录</a><a href="{{helper.createUrl(['p':'salary/payslip'])}}">工资条发放</a><a href="{{helper.createUrl(['p':'salary/report'])}}">报表统计</a><a href="{{helper.createUrl(['p':'salary/log'])}}">操作日志</a><a class="on" href="#">工资表查看</a></div>
	<div class="salary_page">
		<div class="salary_toolbar"><a class="btn" href="{{helper.createUrl(['p':'salary/archive'])}}">返回归档记录</a></div>
		<div class="salary_tip">工资月份：{{archiveItem['payroll_month']}}　人数：{{archiveItem['employee_count']}}　应发总额：{{archiveItem['earning_total']}}　应扣总额：{{archiveItem['deduction_total']}}　实发总额：{{archiveItem['net_total']}}</div>
		<div class="salary_scroll"><table class="salary_table"><tr><th class="salary_name">员工</th><th class="salary_mobile">手机号</th><th class="salary_department">部门</th>{% for project in archiveDisplayProjects %}<th class="archive_{{project['initial_group']}} salary_project" title="{{project['name']}}"><span class="salary_two_line">{{project['name']}}</span></th>{% endfor %}</tr>
		{% for row in archiveRows %}<tr><td class="salary_name"><span class="salary_two_line">{{row['employee_name']}}</span></td><td class="salary_mobile"><span class="salary_two_line">{{row['employee_no']}}</span></td><td class="salary_department"><span class="salary_two_line">{{row['department_name']}}</span></td>{% for project in archiveDisplayProjects %}<td class="archive_{{project['initial_group']}}">{% if row['values'][project['value_key']] is defined %}{{row['values'][project['value_key']]}}{% elseif project['is_text_project'] %}{% else %}0.00{% endif %}</td>{% endfor %}</tr>{% elsefor %}<tr><td colspan="40">归档工资表暂无员工数据</td></tr>{% endfor %}
		</table></div>
	</div>
</div>
